In [1]:
#Mount my drive- run the code, go to the link, accept.
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [2]:
#Change working directory to make it easier to access the files
import os
os.chdir("/content/gdrive/My Drive/Colab Notebooks/")
os.getcwd()

'/content/gdrive/My Drive/Colab Notebooks'

# PCA Analysis for Principal Components
##### Data can be found at:https://www.kaggle.com/ronitf/heart-disease-uci#heart.csv


### Heart Disease Data

#### Description of features

age: age in years <br>
sex: (1 = male; 0 = female) <br>
cp: chest pain type<br>
trestbps: resting blood pressure (in mm Hg on admission to the hospital)<br>
chol: serum cholestoral in mg/dl<br>
fbs: (fasting blood sugar > 120 mg/dl) (1 = true; 0 = false)<br>
restec: gresting electrocardiographic results<br>
thalach: maximum heart rate achieved<br>
exang: exercise induced angina (1 = yes; 0 = no)<br>
oldpeak: ST depression induced by exercise relative to rest<br>
slope: the slope of the peak exercise ST segment<br>
ca: number of major vessels (0-3) colored by flourosopy<br>
thal: 3 = normal; 6 = fixed defect; 7 = reversable defect<br>
target: 1 or 0<br>

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
%matplotlib inline

In [83]:
data = pd.read_csv("/content/gdrive/My Drive/OwnJupyterNotebooks/heart.csv")
data.head()


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [0]:
data = data.dropna(axis=0)

In [0]:
features = ['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal']
X = data.loc[:, features].values

In [0]:
y = data.loc[:,['target']].values

#### Standardizing the data

In [0]:
X = StandardScaler().fit_transform(X)

In [88]:
pd.DataFrame(data = X, columns = features).head()

age       sex        cp  trestbps      chol       fbs   restecg  \
0  0.952197  0.681005  1.973123  0.763956 -0.256334  2.394438 -1.005832   
1 -1.915313  0.681005  1.002577 -0.092738  0.072199 -0.417635  0.898962   
2 -1.474158 -1.468418  0.032031 -0.092738 -0.816773 -0.417635 -1.005832   
3  0.180175  0.681005  0.032031 -0.663867 -0.198357 -0.417635  0.898962   
4  0.290464 -1.468418 -0.938515 -0.663867  2.082050 -0.417635  0.898962   

    thalach     exang   oldpeak     slope        ca      thal  
0  0.015443 -0.696631  1.087338 -2.274579 -0.714429 -2.148873  
1  1.633471 -0.696631  2.122573 -2.274579 -0.714429 -0.512922  
2  0.977514 -0.696631  0.310912  0.976352 -0.714429 -0.512922  
3  1.239897 -0.696631 -0.206705  0.976352 -0.714429 -0.512922  
4  0.583939  1.435481 -0.379244  0.976352 -0.714429 -0.512922

#### Choosing number of principal components/dimensiona and checking percentage of data retention

In [0]:

pca = PCA(n_components=2)

In [0]:
principal_components = pca.fit_transform(X)

In [0]:

principal_dataframe = pd.DataFrame(data = principal_components
             , columns = ['principal component 1', 'principal component 2'])

In [92]:
principal_dataframe.head(5)

principal component 1  principal component 2
0               0.624111               2.321270
1              -0.455988              -0.957351
2              -1.828805               0.042885
3              -1.716006              -0.495337
4              -0.371356               0.301156

#### Consolidating final data set

In [93]:
type(data['target'][3])

numpy.int64

In [94]:
data['target'] = data['target'].astype(str)
type(data['target'][3])

str

In [95]:
data = data.replace({'target':{'1':'positive','0':'negative'}})
data.head()


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal    target  
0   0     1  positive  
1   0     2  positive  
2   0     2  positive  
3   0     2  positive  
4   0     2  positive

In [96]:
final_dataframe = pd.concat([principal_dataframe, data[['target']]], axis = 1)
final_dataframe.head(5)

principal component 1  principal component 2    target
0               0.624111               2.321270  positive
1              -0.455988              -0.957351  positive
2              -1.828805               0.042885  positive
3              -1.716006              -0.495337  positive
4              -0.371356               0.301156  positive

### Check to see how much of the variance is explained by the top two principal components.

In [97]:
pca.explained_variance_ratio_

array([0.21254053, 0.11820708])

#### Only 32% of the variance is explained by the top two principal components.  It's time to try letting sklearn decide how many components are necessary to explain 95% of the data.

In [0]:
pca = PCA(.95)

In [0]:
features = ['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal']
X = data.loc[:, features].values

In [0]:
y = data.loc[:,['target']].values

In [0]:
X = StandardScaler().fit_transform(X)

In [0]:
principal_components = pca.fit_transform(X)

In [103]:

pca.n_components_

12

#### The optimal number of components for this dataset is 12.

# PCA for Algorithm Efficiency: Using Principle Components to Predict Heart Disease

In [0]:
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [105]:
# Switch labels back into numerical values for regression
data = data.replace({'target':{'positive':'1','negative':'0'}})
data.head(2)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   

   ca  thal target  
0   0     1      1  
1   0     2      1

In [106]:
data['target'] = data['target'].astype(int)
type(data['target'][3])

numpy.int64

In [0]:
y = data['target']

In [0]:
# Splitting data into train and test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=.2, random_state=0)

In [0]:
principal_components = pca.fit_transform(X)

In [110]:
pca.n_components_

12

In [0]:
log_regression = LogisticRegression()

In [112]:
log_regression.fit(X,y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

### Predicting individual patients and a group of patients.

In [113]:
log_regression.predict(X[150].reshape(1,-1))

array([0])

In [114]:
log_regression.predict(X[10:20])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Checking accuracy.

In [115]:
score = log_regression.score(X_test,y_test)
print(score)

0.8688524590163934


#### The accuracy of this model is 86.9%